---
- name: "Configure with kubectl"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENV_NAME: "{{ lookup('env', 'ENV_NAME') }}"
  roles:
    - backend-service-deployment
    - backend-service