Parameters:
  EnvName:
    Description: Environment name
    Default: get-list-backend-service
    Type: String
  SSHKeyName:
    Description: SSH key for management access
    Default: udacity
    Type: String
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-0044130ca185d0880
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvName}-management-SG
      GroupDescription: Allow port 22 for management
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  managementHost1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-management1
        - Key: Project
          Value: !Ref EnvName

  managementHost2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-management2
        - Key: Project
          Value: !Ref EnvName