apiVersion: v1
kind: Service
metadata:
  name: get-list-backend-service
spec:
  type: LoadBalancer
  selector:
    app: get-list-backend-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000